-- Seed bingo items (run after migration)
INSERT INTO public.bingo_items (position, title) VALUES
(0,  'Q''d a beatdown'),
(1,  'Q''d 5 beatdowns'),
(2,  'Brought an FNG'),
(3,  'Brought 3 FNGs'),
(4,  'Completed a pre-run/pre-murph'),
(5,  'Stayed for Coffeteria'),
(6,  'Attended a 2nd F event'),
(7,  'Attended a 3rd F event'),
(8,  'Organized a 2nd F event'),
(9,  'Organized a 3rd F event'),
(10, 'Attended 10 beatdowns'),
(11, 'Attended 20 beatdowns'),
(12, 'FREE SPACE'),
(13, 'Posted at 3 different AOs'),
(14, 'Posted at 5 different AOs'),
(15, 'Posted in all 3 Legacy Regions'),
(16, 'Posted Downrange'),
(17, 'Picked up a leadership role'),
(18, 'Reached out to a kotter'),
(19, 'Attended a Convergence'),
(20, 'Led 30 for 30 or attended'),
(21, 'Attended a Q Source'),
(22, 'Posted in Pax Essay'),
(23, 'Shared a Social Media Post'),
(24, 'Completed a Ruck');
